version: "3.9"

services:
  chess-dev:
    build: .
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"   # web/server.js
      - "3001:3001"   # mockBoardEditor dev server
    environment:
      - PORT=3000
      - MOCK_EDITOR_PORT=3001


